/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'iotanames';

export const ApiKey: Record<Environment, string> = {
  iotanames: '046308c03d97539ea94cefe036142905'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '1',
    branch: 'main',
    source: 'web',
    versionId: 'd1206ad7-730b-40f8-ab26-ced8dfa98962'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  },
  serverZone: amplitude.Types.ServerZone.EU
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface AddressConnectProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Enum Values | current, external |
   */
  "connect address type": "current" | "external";
  name: string;
}

export interface AuctionBidProperties {
  name: string;
}

export interface AuctionBidAgainProperties {
  name: string;
}

export interface AuctionFilterNamePerformedProperties {
  query: string;
}

export interface AuctionStartProperties {
  name: string;
}

export interface NameBuyProperties {
  name: string;
}

export interface NameRenewalProperties {
  duration: string;
  name: string;
}

export interface NameSetAsDisplayedProperties {
  name: string;
}

export interface SearchPerformedProperties {
  query: string;
}

export interface SubnameCreateProperties {
  name: string;
}

export class AddressConnect implements BaseEvent {
  event_type = 'address connect';

  constructor(
    public event_properties: AddressConnectProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AuctionBid implements BaseEvent {
  event_type = 'auction bid';

  constructor(
    public event_properties: AuctionBidProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AuctionBidAgain implements BaseEvent {
  event_type = 'auction bid again';

  constructor(
    public event_properties: AuctionBidAgainProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AuctionFilterNamePerformed implements BaseEvent {
  event_type = 'auction filter name performed';

  constructor(
    public event_properties: AuctionFilterNamePerformedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AuctionStart implements BaseEvent {
  event_type = 'auction start';

  constructor(
    public event_properties: AuctionStartProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class NameBuy implements BaseEvent {
  event_type = 'name buy';

  constructor(
    public event_properties: NameBuyProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class NameRenewal implements BaseEvent {
  event_type = 'name renewal';

  constructor(
    public event_properties: NameRenewalProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class NameSetAsDisplayed implements BaseEvent {
  event_type = 'name set as displayed';

  constructor(
    public event_properties: NameSetAsDisplayedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SearchPerformed implements BaseEvent {
  event_type = 'search performed';

  constructor(
    public event_properties: SearchPerformedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SubnameCreate implements BaseEvent {
  event_type = 'subname create';

  constructor(
    public event_properties: SubnameCreateProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * address connect
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/address%20connect)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. connect address type)
   * @param options Amplitude event options.
   */
  addressConnect(
    properties: AddressConnectProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddressConnect(properties), options);
  }

  /**
   * auction bid
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/auction%20bid)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  auctionBid(
    properties: AuctionBidProperties,
    options?: EventOptions,
  ) {
    return this.track(new AuctionBid(properties), options);
  }

  /**
   * auction bid again
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/auction%20bid%20again)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  auctionBidAgain(
    properties: AuctionBidAgainProperties,
    options?: EventOptions,
  ) {
    return this.track(new AuctionBidAgain(properties), options);
  }

  /**
   * auction filter name performed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/auction%20filter%20name%20performed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. query)
   * @param options Amplitude event options.
   */
  auctionFilterNamePerformed(
    properties: AuctionFilterNamePerformedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AuctionFilterNamePerformed(properties), options);
  }

  /**
   * auction start
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/auction%20start)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  auctionStart(
    properties: AuctionStartProperties,
    options?: EventOptions,
  ) {
    return this.track(new AuctionStart(properties), options);
  }

  /**
   * name buy
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/name%20buy)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  nameBuy(
    properties: NameBuyProperties,
    options?: EventOptions,
  ) {
    return this.track(new NameBuy(properties), options);
  }

  /**
   * name renewal
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/name%20renewal)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. duration)
   * @param options Amplitude event options.
   */
  nameRenewal(
    properties: NameRenewalProperties,
    options?: EventOptions,
  ) {
    return this.track(new NameRenewal(properties), options);
  }

  /**
   * name set as displayed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/name%20set%20as%20displayed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  nameSetAsDisplayed(
    properties: NameSetAsDisplayedProperties,
    options?: EventOptions,
  ) {
    return this.track(new NameSetAsDisplayed(properties), options);
  }

  /**
   * search performed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/search%20performed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. query)
   * @param options Amplitude event options.
   */
  searchPerformed(
    properties: SearchPerformedProperties,
    options?: EventOptions,
  ) {
    return this.track(new SearchPerformed(properties), options);
  }

  /**
   * subname create
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/subname%20create)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  subnameCreate(
    properties: SubnameCreateProperties,
    options?: EventOptions,
  ) {
    return this.track(new SubnameCreate(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
