[package]
name = "denylist"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x7bdffb4cff0666126d2426409b87192b8633b6647ce6d813b7cdab0c2a1517a1"

[dependencies]
# IOTA = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet", override=true }
Iota = { local = "../../../iota/crates/iota-framework/packages/iota-framework" }
iotans = { local = "../iotans" }


[addresses]
denylist = "0x7bdffb4cff0666126d2426409b87192b8633b6647ce6d813b7cdab0c2a1517a1"