[package]
name = "denylist"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "64e8125", override = true }
IotaNames = { local = "../iota-names" }

[addresses]
denylist = "0x0"
