[default]
extend-ignore-identifiers-re = [
  # Short git hashes
  "^[a-f0-9]{7}$",
  "^[a-f0-9]{12}$",
  # Base64
  "^[a-zA-Z0-9_]{43}$",
  "^[a-zA-Z0-9_]{44}$",
  "^[a-zA-Z0-9_]{47}$",
  "^[a-zA-Z0-9_]{49}$",
  "^[a-zA-Z0-9_]{56,}$",
  # Allow "packageid"
  "^packageid$",
]

[files]
extend-exclude = [
  "scripts/init/labels-to-block.txt",
  "scripts/init/labels-to-reserve.txt",
  "scripts/init/names-to-register.csv",
]
