[package]
name = "payments"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }
IotaNames = { local = "../iota-names" }

[addresses]
iota_names_payments = "0x0"
