[package]
name = "coupons"
version = "0.0.1"
edition = "2024.beta"
published-at="0x6d14ca3049be747ec87166e6dce5d0d9a30f3b3c281c55d6e518958a236f8b97"

[dependencies]
# IOTA = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/mainnet", override=true }
Iota = { local = "../../../iota/crates/iota-framework/packages/iota-framework" }
iotans = { local = "../iotans" }
# iotans = { git = "https://github.com/iotaledger/iotans-contracts/", subdir = "packages/iotans", rev = "releases/mainnet/core/v3" }

[addresses]
coupons = "0x6d14ca3049be747ec87166e6dce5d0d9a30f3b3c281c55d6e518958a236f8b97"
