[package]
name = "coupons"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x66ab98b0886b1867470d15450259c209147b1727db7c8bd579c13a2d0d52f88e"

[dependencies]
# IOTA = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet", override=true }
Iota = { local = "../../../iota/crates/iota-framework/packages/iota-framework" }
iotans = { local = "../iotans" }


[addresses]
coupons = "0x66ab98b0886b1867470d15450259c209147b1727db7c8bd579c13a2d0d52f88e"