[package]
name = "subdomains"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet", override = true }
IotaNames = { local = "../iota-names" }
deny_list = { local = "../deny-list" }

[addresses]
subdomains = "0x0"
