[package]
name = "iota_names_subdomains"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet", override = true }
iota_names = { local = "../iota-names" }
iota_names_deny_list = { local = "../deny-list" }

[addresses]
iota_names_subdomains = "0x0"
