{
 "title": "IOTA-Names (InfluxDB)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processed Checkpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_ingestion_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Name Records ever created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"name_record_added\" and r._field == \"length\")\n  |> group()\n  |> count()\n  |> rename(columns: {_value: \"Total\"})"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "IOTA-Names Balance",
   "type": "timeseries",
   "description": "The IOTA balance of the IotaNames object.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"balance\" and r.source == \"iota_names\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000000.0}))\n  |> set(key: \"_field\", value: \"Balance in IOTA\")"
    }
   ]
  },
  {
   "title": "Total Name Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "query": "added = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"name_record_added\" and r._field == \"length\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Record Count\", _measurement: \"records\"}))\n\nremoved = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"name_record_removed\" and r._field == \"length\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"Record Count\", _measurement: \"records\"}))\n\nunion(tables: [added, removed])\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    }
   ]
  },
  {
   "title": "Subname Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "query": "created = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"node_subname_created\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Node Subnames\", _measurement: \"subnames\"}))\n\nburned = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"node_subname_burned\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"Node Subnames\", _measurement: \"subnames\"}))\n\nunion(tables: [created, burned])\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    },
    {
     "query": "created = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"leaf_subname_created\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Leaf Subnames\", _measurement: \"subnames\"}))\n\nremoved = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"leaf_subname_removed\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"Leaf Subnames\", _measurement: \"subnames\"}))\n\nunion(tables: [created, removed])\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    }
   ]
  },
  {
   "title": "Target addresses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "set = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"target_address_set\" and r._field == \"set\")\n  |> map(fn: (r) => ({_time: r._time, _value: if r._value then 1 else -1, _field: \"Target Addresses\", _measurement: \"target_addresses\"}))\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    }
   ]
  },
  {
   "title": "Default names",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "query": "setEvt = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"reverse_lookup_set\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Default Names\", _measurement: \"defaults\"}))\n\nunsetEvt = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"reverse_lookup_unset\" and r._field == \"name\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"Default Names\", _measurement: \"defaults\"}))\n\nunion(tables: [setEvt, unsetEvt])\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    }
   ]
  },
  {
   "title": "Proportion of node/leaf subnames",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "created = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"node_subname_created\" and r._field == \"name\")\n  |> group()\n  |> count()\n  |> set(key: \"_field\", value: \"Node\")\n\nburned = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"node_subname_burned\" and r._field == \"name\")\n  |> group()\n  |> count()\n  |> set(key: \"_field\", value: \"node_burned\")\n\nnodeTotal = join(tables: {created: created, burned: burned}, on: [\"_field\"], method: \"inner\")\n\nfrom(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"node_subname_created\" and r._field == \"name\")\n  |> group()\n  |> count()\n  |> set(key: \"_field\", value: \"Node\")"
    },
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"leaf_subname_created\" and r._field == \"name\")\n  |> group()\n  |> count()\n  |> set(key: \"_field\", value: \"Leaf\")"
    }
   ]
  },
  {
   "title": "Coupon discounts",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"coupon_applied\" and r._field == \"discount\" and r.kind == \"percentage\")\n  |> group()\n  |> sum()\n  |> set(key: \"_field\", value: \"Percentage\")"
    },
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"coupon_applied\" and r._field == \"discount\" and r.kind == \"fixed\")\n  |> group()\n  |> sum()\n  |> set(key: \"_field\", value: \"Fixed\")"
    }
   ]
  },
  { "title": "Distributions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of years per renewal",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"transaction\" and r._field == \"years\" and r.is_renewal == \"true\")\n  |> group()\n  |> histogram(bins: [1.0, 2.0, 3.0, 4.0, 5.0])"
    }
   ]
  },
  {
   "title": "Count per second level name length",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nadded = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"name_record_added\" and r._field == \"length\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"count\", length: string(v: r._value)}))\n\nremoved = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"name_record_removed\" and r._field == \"length\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"count\", length: string(v: r._value)}))\n\nunion(tables: [added, removed])\n  |> group(columns: [\"length\"])\n  |> sum()\n  |> group()"
    }
   ]
  },
  {
   "title": "Name depth",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "query": "added = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"name_record_added\" and r._field == \"depth\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"count\", depth: string(v: r._value)}))\n\nremoved = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"name_record_removed\" and r._field == \"depth\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"count\", depth: string(v: r._value)}))\n\nunion(tables: [added, removed])\n  |> group(columns: [\"depth\"])\n  |> sum()\n  |> group()"
    }
   ]
  },
  {
   "title": "User data keys",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "setEvt = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"user_data_set\" and r._field == \"new\" and r._value == true)\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"count\", key: r.key}))\n\nunsetEvt = from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"user_data_unset\" and r._field == \"count\")\n  |> map(fn: (r) => ({_time: r._time, _value: -1, _field: \"count\", key: r.key}))\n\nunion(tables: [setEvt, unsetEvt])\n  |> group(columns: [\"key\"])\n  |> sum()\n  |> group()"
    }
   ]
  },
  { "title": "Auctions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Auction House Balance",
   "type": "timeseries",
   "description": "The IOTA balance of the AuctionHouse object.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"balance\" and r.source == \"auction_house\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000000.0}))\n  |> set(key: \"_field\", value: \"Balance in IOTA\")"
    }
   ]
  },
  {
   "title": "Auction durations",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"auction_finalized\" and r._field == \"duration_ms\")\n  |> set(key: \"_field\", value: \"Duration (ms)\")"
    }
   ]
  },
  {
   "title": "Average auction duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"auction_finalized\" and r._field == \"duration_ms\")\n  |> group()\n  |> mean()"
    }
   ]
  },
  {
   "title": "Number of auctions started and finalized",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "started = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"auction_started\" and r._field == \"starting_bid\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Auctions Started\", _measurement: \"auctions\"}))\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)\n\nstartedCount = from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"auction_started\" and r._field == \"starting_bid\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"_tmp\", _measurement: \"auctions\"}))\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)\n\nstarted"
    },
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"auction_finalized\" and r._field == \"winning_bid\")\n  |> map(fn: (r) => ({_time: r._time, _value: 1, _field: \"Auctions Finalized\", _measurement: \"auctions\"}))\n  |> group(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()\n  |> filter(fn: (r) => r._time >= v.timeRangeStart)"
    }
   ]
  },
  {
   "title": "Final auction prices",
   "type": "histogram",
   "description": "Bucket size is 1 IOTA",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "NANOs" } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"auction_finalized\" and r._field == \"winning_bid\")\n  |> set(key: \"_field\", value: \"Price\")"
    }
   ]
  },
  {
   "title": "Average auction price",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "IOTA" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"auction_finalized\" and r._field == \"winning_bid\")\n  |> group()\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000000.0}))\n  |> mean()"
    }
   ]
  },
  {
   "title": "Auctions per number of bids",
   "type": "barchart",
   "description": "Shows how many auctions received a certain number of bids.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "import \"experimental\"\n\nfrom(bucket: \"iota-names\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"auction_started\" and r._field == \"name\")\n  |> group(columns: [\"_value\"])\n  |> count()\n  |> rename(columns: {_value: \"bid_count\"})\n  |> group()"
    }
   ]
  }
 ]
}