[package]
name = "auction"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet", override = true }
IotaNames = { local = "../iota-names" }

[addresses]
iota_names_auction = "0x0"
