name: dprint format

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: dprint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  run:
    name: Check dprint format
    runs-on: self-hosted
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check
        run: dprint check
