name: Indexer CI

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/indexer.yaml"
      - "indexer/**"

concurrency:
  group: indexer-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  lint:
    name: Lint indexer crate
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check format
        run: cargo +nightly-2025-04-01 fmt --check --manifest-path indexer/Cargo.toml

      - name: Check udeps
        run: cargo +nightly-2025-04-01 udeps --manifest-path indexer/Cargo.toml

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --manifest-path indexer/Cargo.toml -- -D warnings

  bans-licenses-sources:
    name: Cargo deny (bans, licenses, sources)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: cargo deny --manifest-path indexer/Cargo.toml check bans licenses sources --hide-inclusion-graph

  advisories:
    name: Cargo deny (advisories)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: cargo deny --manifest-path indexer/Cargo.toml check advisories --hide-inclusion-graph

  check:
    name: Check indexer crate
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: cargo check --all-targets --all-features --manifest-path indexer/Cargo.toml
