name: Build IOTA-Names TX

on:
  workflow_dispatch:
    inputs:
      network:
        description: "select the network to use"
        type: choice
        options:
          - mainnet
          - testnet
          - devnet
      transaction_type:
        description: "select transaction type to create"
        type: choice
        options:
          - Profits to Treasury
          - Transfer Reserved Names
          - Transfer IOTA-Names Admin Objects
          - Upgrade IOTA-Names
      iota_tools_image:
        description: "image reference of iota_tools"
        default: "iotaledger/iota-tools:mainnet"
      rpc:
        description: "RPC url"
        required: true
        default: "https://api.mainnet.iota.cafe:443"
        type: string
      recipient_address:
        description: "address to send profits or admin objects to"
        required: false
        type: string
        default: "0x1ca3c38e888493f869ac35346a2041d6cf87b0b935ebba14b35a08811d8a76e4"

jobs:
  iota_names:
    name: IOTA-Names create tx
    runs-on: ubuntu-latest

    steps:
      - name: Selected transaction type
        run: |
          echo ${{ inputs.transaction_type }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install IOTA using Homebrew
        run: brew install iotaledger/tap/iota

      - name: YAML Setup
        run: |
          iota client --yes new-env --rpc ${{ inputs.rpc }} --alias network

      - name: NPM BUILD TX Environment
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 18

      - name: Do a global PNPM install
        run: |
          npm install -g pnpm

      - name: Set up working directory
        run: |
          pnpm install

      - name: Profits to Treasury
        if: ${{ inputs.transaction_type == 'Profits to Treasury' }}
        env:
          NODE_ENV: production
          NETWORK: ${{ inputs.network }}
          ORIGIN: gh_action
        run: |
          cd scripts && pnpm withdraw:profits ${{ inputs.recipient_address }}

      - name: Transfer Reserved Names
        if: ${{ inputs.transaction_type == 'Transfer Reserved Names' }}
        env:
          NODE_ENV: production
          NETWORK: ${{ inputs.network }}
          ORIGIN: gh_action
        run: |
          cd scripts && pnpm transfer::names

      - name: Transfer IOTA-Names Admin Objects (Admin Cap, Package UpgradeCaps, Publisher, Display)
        if: ${{ inputs.transaction_type == 'Transfer IOTA-Names Admin Objects' }}
        env:
          NODE_ENV: production
          NETWORK: ${{ inputs.network }}
          ORIGIN: gh_action
        run: |
          cd scripts && pnpm transfer::admin-objects ${{ inputs.recipient_address }}

      - name: Upgrade IOTA-Names
        if: ${{ inputs.transaction_type == 'Upgrade IOTA-Names' }}
        env:
          NODE_ENV: production
          NETWORK: ${{ inputs.network }}
          ORIGIN: gh_action
          RPC_URL: ${{ inputs.rpc }}
        run: |
          cd scripts && pnpm ts-node transactions/upgrade-iota-names.ts

      - name: Show Transaction Data (To sign)
        run: |
          cat scripts/tx/tx-data.txt

      - name: Upload Transaction Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: transaction-data
          path: scripts/tx
