---
name: IOTA-Names - Combine and Execute Multi-Sig TX

on:
  workflow_dispatch:
    inputs:
      rpc:
        description: "RPC for the IOTA client"
        required: true
        default: "https://api.mainnet.iota.cafe:443"
        type: string
      iota_tools_image:
        description: "image reference of iota_tools"
        default: "iotaledger/iota-tools:mainnet"
        required: true
        type: string
      all_pks:
        description: "ordered pubkeys (separate by spaces)"
        required: true
        type: string
        default: "AFJ/IT8eh3zYqax/EkoSWqBbbE+FY5Abeaana2ffzpy1 AIQRbyXfJYqMCrOunqJI3JtDfIldeMmU4G0/5FlXbqba AG+hXBtpV+kOmGfTWT1X4Bz7Hjdo+dwhT8vWoONd0Bwl AQIbWcxmj/KNVEfjps2w90UMVdNQG2P07bQJUrqVYllupg== AKQfMrarpsxpq4zq6XMzFhvqGPU9zNjUTd9KnhXEEvfT"
      all_sigs:
        description: "All ordered signatures (separate by spaces)"
        required: true
        type: string
        default: ""
      weights:
        description: "weights for each key"
        required: true
        default: "1 1 1 1 1"
        type: string
      threshold:
        description: "multisig account threshold"
        required: true
        default: "3"
        type: string
      test_data_only:
        description: "Just a test for data output from artifacts"
        required: true
        default: false
        type: boolean
      execute_tx:
        description: "execute combined musig tx"
        required: true
        default: false
        type: boolean

jobs:
  iota_names_combine_and_execute:
    name: IOTA-Names Combine and Execute tx
    runs-on: ubuntu-latest

    steps:
      - name: Create client.yaml and keystore
        working-directory: .
        env:
          NETWORK: mainnet
          RPC: ${{ inputs.rpc }}
        run: |
          mkdir iota_config
          touch iota_config/iota.keystore
          cat <<EOF > iota_config/iota.keystore
          [
            "iotaprivkey1qrhwwskzlay56kddyanq7jcptzy5cmrp5lr2rvxvtlaxfs5cnvrlxdx89cr"
          ]
          EOF
          cat <<EOF > iota_config/client.yaml
          ---
          keystore:
            File: $HOME/.iota/iota_config/iota.keystore
          envs:
            - alias: $NETWORK
              rpc: "$RPC"
              ws: ~
          EOF
          mkdir $HOME/.iota
          cp -r iota_config $HOME/.iota/iota_config

      - name: Set up iota environment
        working-directory: .
        run: |
          docker pull docker.io/${{ inputs.iota_tools_image }}
          docker create --name tmp_cont docker.io/${{ inputs.iota_tools_image }}
          docker cp tmp_cont:/usr/local/bin/iota iota

      - name: Install JQ
        working-directory: .
        run: |
          sudo apt update -y && sudo apt install -y jq

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
        with:
          workflow: iota_names_build_tx.yml
          workflow_conclusion: success
          name: transaction-data
          path: scripts/tx

      - name: Transaction Data being executed
        run: |
          cat scripts/tx/tx-data.txt

      - name: Combine tx
        if: ${{ !inputs.test_data_only }}
        run: |
          set -x
          ALL_PKS="${{ inputs.all_pks }}"
          ALL_SIGS="${{ inputs.all_sigs }}"
          echo "debug"
          echo $ALL_PKS
          echo $ALL_SIGS
          combined_musig="$(./iota keytool multi-sig-combine-partial-sig \
            --pks $(echo $ALL_PKS) \
            --weights $(echo ${{ inputs.weights }}) \
            --threshold $(echo ${{ inputs.threshold }}) \
            --sigs $(echo $ALL_SIGS) --json | jq .multisigSerialized | tr -d \" )"
          echo $ALL_PKS > scripts/tx/pks.txt
          echo $ALL_SIGS > scripts/tx/sigs.txt
          echo $combined_musig > scripts/tx/combined_musig.txt

      - name: execute signed tx
        if: ${{ !inputs.test_data_only && inputs.execute_tx }}
        run: |
          set -x
          echo "combined musig"
          echo "$(cat scripts/tx/combined_musig.txt)"
          result="$(./iota client execute-signed-tx \
            --tx-bytes $(cat scripts/tx/tx-data.txt) \
            --signatures $(cat scripts/tx/combined_musig.txt))"
          echo $result > scripts/tx/result.txt
          cat scripts/tx/result.txt

      - name: Upload Transaction Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: combine-and-execute-transaction
          path: scripts/tx
