name: Lint and Test Move Packages

on:
  pull_request:
    paths:
      - ".github/workflows/move_packages.yml"
      - "packages/**"
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install prettier plugin
        run: npm i -g prettier @mysten/prettier-plugin-move

      - name: Run format check
        run: prettier-move -c packages/**
  
  test:
    runs-on: ubuntu-latest
    needs: format
    if: (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install IOTA using Homebrew
        run: brew install iotaledger/tap/iota

      - name: Run move tests in all package subdirectories, with exclusions
        run: |
          for dir in packages/*; do
            dir_name=$(basename "$dir")
            echo "Running iota move build in $dir"
            iota move build --path "$dir" --lint --warnings-are-errors --dev

            echo "Running iota move test in $dir"
            iota move test --path "$dir"
          done
