name: Move Test CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/move_test.yaml'
      - 'packages/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install IOTA
        run: cargo install --locked --git https://github.com/iotaledger/iota --rev 9e4143f5324c16a9ca0b13126da158672f5c4101 iota

      - name: Run move tests in all package subdirectories, with exclusions
        run: |
          exclude_dirs=(governance) # Add excluded directories to this array
          for dir in packages/*; do
            dir_name=$(basename "$dir")
            if [[ ! " ${exclude_dirs[@]} " =~ " ${dir_name} " ]] && [ -d "$dir" ]; then
              echo "Running iota move test in $dir"
              (cd "$dir" && iota move test)
            fi
          done
