name: Move Test CI

on:
  pull_request:
    paths:
      - ".github/workflows/move_test.yaml"
      - "packages/**"
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install IOTA using Homebrew
        run: brew install iotaledger/tap/iota

      - name: Run move tests in all package subdirectories, with exclusions
        run: |
          for dir in packages/*; do
            dir_name=$(basename "$dir")
            echo "Running iota move build in $dir"
            iota move build --path "$dir" --lint --warnings-are-errors --dev

            echo "Running iota move test in $dir"
            iota move test --path "$dir"
          done
