name: Lint move files

on:
  pull_request:
    paths:
      - ".github/workflows/move_lint.yaml"
      - "packages/**"
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install prettier plugin
        run: npm i -g prettier @mysten/prettier-plugin-move

      - name: Run format check
        run: prettier-move -c packages/**
