name: Names Display CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "names-display/**"
      - ".github/workflows/names-display-ci.yml"
  push:
    paths:
      - "names-display/**"
      - ".github/workflows/names-display-ci.yml"

jobs:
  test:
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: self-hosted-x64
    defaults:
      run:
        working-directory: ./names-display
    steps:
      - name: checkout code repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./
      - name: Build sdk
        run: pnpm --filter @iota/iota-names-sdk run build
      - name: Build names-display service
        run: pnpm --filter names-display run build
        working-directory: ./
      - name: Run names-display tests
        run: pnpm --filter names-display run test
        working-directory: ./
