name: SDK Tests CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/sdk_test.yaml'
      - 'sdk/**'
      - 'packages/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk_test:
    name: SDK Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install IOTA
        run: cargo install --locked --git https://github.com/iotaledger/iota --rev 9e4143f5324c16a9ca0b13126da158672f5c4101 iota

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Do a global PNPM install
        run: |
          npm install -g pnpm

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Prepare local network & run SDK tests
        env: 
          IS_CI_JOB: true
          NETWORK: localnet
        run: |
          iota start --with-faucet --force-regenesis --epoch-duration-ms 120000 > /dev/null 2>&1 & cd sdk && VITE_IOTA_BIN="iota" pnpm test:e2e
