name: Reusable Vercel Deploy

on:
  workflow_call:
    inputs:
      VERCEL_ENVIRONMENT:
        type: string
        required: true
        description: "The Vercel environment to deploy to. Can be 'production' or 'preview'."
      NAMES_DAPP_CONFIG:
        type: string
        required: true
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_SCOPE:
        required: true
      VERCEL_ALIAS:
        required: false
      NAMES_DAPP_DEFAULT_NETWORK:
        required: true

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_ENVIRONMENT: ${{ inputs.VERCEL_ENVIRONMENT }}
  NEXT_PUBLIC_NAMES_DAPP_CONFIG: ${{ inputs.NAMES_DAPP_CONFIG }}
  NEXT_PUBLIC_NAMES_DEFAULT_NETWORK: ${{ inputs.NAMES_DAPP_DEFAULT_NETWORK }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ inputs.VERCEL_ENVIRONMENT != 'production' }}

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

      - name: Install Vercel CLI
        run: pnpm add --global vercel@canary

      - name: Deploy to Vercel
        uses: iotaledger/deploy-to-vercel-action@9c73fe8ff3eb32d6ba30d623ac1b0c5708a25bb7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DELETE_EXISTING_COMMENT: true
          VERCEL_TARGET: ${{ inputs.VERCEL_ENVIRONMENT }}
          CREATE_COMMENT: ${{ inputs.VERCEL_ENVIRONMENT == 'preview' }}
          VERCEL_ALIAS: ${{ inputs.VERCEL_ALIAS || '' }}
